management.endpoints.web.expose.include=health,info
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/

spring.main.allow-circular-references=true

# AWS Secrets Manager Configuration
aws.secrets.enabled=true
aws.secrets.region=ap-southeast-2
aws.secrets.access-key=${AWS_ACCESS_KEY_ID:}
aws.secrets.secret-key=${AWS_SECRET_ACCESS_KEY:}
aws.secrets.session-token=${AWS_SESSION_TOKEN:}